((nil . ((indent-tabs-mode . nil)
         (fill-column . 70)
         (sentence-end-double-space . t)))
 (org-mode . ((mode . auto-fill)
              (org-hugo-front-matter-format . "yaml")
              (org-hugo-preserve-filling . nil)
              (org-hugo-use-code-for-kbd . t)
              (org-hugo-export-with-toc . t)
              (org-hugo-export-with-section-numbers . t)
              (org-hugo-date-format . "%Y-%m-%d")
              (org-hugo-default-section-directory . "notes")
              (eval . (org-hugo-auto-export-mode)))))
