#+title: Clojure
#+HUGO_BASE_DIR: /Users/matias/Development/matiasfha/brain/
#+HUGO_SECTION: notes
- tags:: [[file:20200927000334-programing_languages.org][Programing Languages]]
* Nacido el 2007, actualmente mantenido por Cognitect con 126 contributors formales
* Un lenguaje robusto, practico y rápido con caracterísiticas para forma una herramienta simple, coherente y poderosa.
* De propósito general,
* Interoperabilidad con Java
* Es un dialecto de Lisp y comparte la filosofía codigo-como-datos
** Esto se conoce como homoiconocidad. El propio programa ecrito puede ser manipulado como data usando el propio lenguaje.
* Funcional
* Estructuras de datos inmutables
* Polimorfismo
* Soporta Macros
** Provee la oporatuniad de extender el lenguaje
* Confiable and Battle tested: Utilizado por Citibank, Simple, Amazon, Netflix, etc.
* Se ejecuta en la JVM
* Gran comunidad, un ejemplod ello es el project [[https://github.com/athensresearch/ClojureFam][ClojureFam]] del que participo para aprender Clojure
* Tiene dos conferencias anuales US para un total de entre 7 y 8 conferencias mundiales (incluyendo una remota)
** También puede ser usado en el browser con Clojurecript, un compilador de Clojure que crea código JS
