#+TITLE: How to take smart notes
#+CREATED: [2020-09-25 Fri 02:16]
#+LAST_MODIFIED: [2020-09-25 Fri 02:16]
#+HUGO_BASE_DIR: /Users/matias/Development/matiasfha/braindump.matiashernandez.dev
- tags: [[file:20200928121101-writing.org][Writing]]
* Introduction
*- every intellectual endeavour starts with a note.
** improving the organisation of all writing makes a difference
- The queality of a paper and the ease with which it is written depends more than anything on what you have done in writing before you even made a decision on the topic**
*- Routines require simple, repeatable tasks that can become automatic and fit together seamlessly
** writing is not a linear process
*- Even the best tools won't make much of a difference if they are used in isolation.
** Only if you can trust your system will your brain let go and let you focus on the task at hand.
- One idea, one note is only as valuable as its context, which is not necesarily the context it was taken from.
> Even hard work can be fun as long as it is aligned with our intrinsic goals and we feel in control.
> Only if thw work is set up in a way that is flexible enough to allow these small and constant adjustments can we keep our interest, motiviation and worl aligned - which is the precondition to effortless or almost effortless work.

- Success is not the result of strong willpower and the ability to overcome resistance, but rather the result of smart working environments that avoid resistance in the first place (cf Neat et al 2012; Painter et al. 2002, Hearn et al 1998)

- Every time a note is added check the slip-box for other relevant notes to make it possible connections between them.
- Keep an index to refer to some kind of an entry point to a ling of thought or topic

  #+BEGIN_QUOTE
Nobody starts from scratch and everybody is already able to think for themselves.
  #+END_QUOTE

This is the basic/general idea of the slipbox. Every new idea comes from a set of other ideas that were stored in the slipbox.

#+BEGIN_QUOTE
Tools are only as good as your ability to work with them.
#+END_QUOTE
The slipbox is a tool, but is important to understand how to include the technique inside the routing (like the review of fleeting notes) to really harness the power of it.


#+BEGIN_QUOTE
An idea kept private is good as one you never had
#+END_QUOTE

The idea of this tooling is to be able to move faster and publish ideas to finally be able to gather feedback
