#+TITLE: Post: Lenguajes de Programación Moderno
#+CREATED: [2020-09-23 Wed 15:16]
#+LAST_MODIFIED: [2020-09-23 Wed 15:16]
#+public: true
* tags::  [[file:20200922032244-clojure.org][Clojure]] [[file:20200920112829-elm.org][Elm]] [[file:20200920163655-elixir.org][Elixir]] [[file:20200920112816-rust.org][Rust]] [[file:20200923151657-posts.org][Posts]]
:PROPERTIES:
:ID:       a660e678-3519-4f70-bc8d-ce8646d0ee03
:END:


* Outline [2/4]
** [X] Intro
Existen muchos lenguajes de programación, quizá demasiados, cada uno enfocado a solucionar algún problema en particular o con alguna orientación diferente. Algunos de estos han sucumbido a los cambios y otros se han mantenido estoicos durante los años y unos pocos han superado todo cambio y son parte escencial de la tecnología que usamos hoy en día.
Entre estos añosos monstruos tenemos C, nacido en 1972, C++ en 1985, Java, Javascript, Python, Php, Ruby, todos ellos nacidos en los 90. Si bien estos leguajes aún siguen en boga y tienen un gran mercado, es fácil ver que se han vuelto muy complejos a la hora de enfrentar los problemas de hoy en día
** [X] Content
El término **moderno** es una clasificación a lo menos controversial, es complejo definir que es moderno ya que cada uno puede tener prejucios y preconceptos sobre que considerar actual o no, pero en el scope de este post consideraremos modernos a lenguajes nacidos durante la **última  decada** y que contemplan algunas características que en general la comunidad de desarrolladores a llegado a desear y definir como básicos.

*** La necesidad de la invención
La tecnología de hoy es, claramente, diferente a la de hace 40-50 año, hoy los sistemas y aplicaciones deben soportar computadores **multi-core**, uso de **gpu**, dispositivos móvules, **cloud computing**, etc. En general, un concepto que engloba estos términos es **Concurrencia**.
La mayoría de los lenguajes _antiguos_ se han actualizado con los años para dar soporte a estos nuevos requerimientos, por ejemplo Java agregó expresions Lambda y Streams en su versión 8. El problema es que estos lenguajes no fueron diseñados con estos requerimientos en mente.
Es por esto que cada año vemos el nacimiento de algún nuevo lenguaje que incluye alguna característica especial que le da vida, dentro de este grupo hay algunos lenguajes que destacan por los diferentes approaches que proponen para enfrentar los problemas de la tecnología actual.

Algunas de estas características son:
- Soporte nativo para concurrencia
- Inmutabilidad
- Inferencia de tipos y type safety
- Programación funcional,
- Tipos estáticos
- Nuevos tipos de sintaxis
- Developer Experience

Algunos de estos lenguajes, que en base a estas caracterísitcas, se muestran como **modernos** son:
- Rust
- Elm
- Clojure
- Elixir
- Kotlin
- Swift
- Scala
- Grain
- Unison
- Dark

  Lo que sigue es un overview de algunos de estos lenguajes, describiendo algunos de los features que cada uno de ellos presenta, me enconfaré en Rust, Elm y Clojure. Intencionalmente me he dejado fuera Kotlin y Swift.
  Kotlin y Swift son claramente lenguajes modernos,nacieron para cubrar una necesidad moderna, desarrollar aplicaciones móviles, los dejo fuera de este listado por que:
  - Tienen un futuro claro
  - Son lenguajes de nicho (cada uno para su plataforma)

** TODO Overview
Comenzaremos esta lista con **Rust** un lenguaje que considero tiene un gran potencial y que ha crecido enormemente tanto en su set de características como en el tamaaño de su comunidad.

*** Rust
Se autodefine como un lenguaje para **empoderar a todos a construir software confiable y eficiente**, nace como una alternativa a C++. Es un lenguaje de uso general, se puede usar para casi todo, incluyendo aplicaciones web al compilar como wasm.

Uno de sus objetivos es ser eficitiente y tener una gran performance en runtime. Otras de sus características son:

**** Compila como binario, no tiene garbage collector es como C++
**** Tiene interoperación con C/C++
**** Tiene un manejador de paquetes, plugins para editores, material de aprendizaje (ej: https://github.com/rust-lang/rustlings y [esta colección en egghead](https://egghead.io/playlists/learning-rust-by-solving-the-rustlings-exercises-a722?af=4cexzz) por [Chris Biscardi](https://www.christopherbiscardi.com/the-rust-programming-language))
**** Es Backward compatible
***
Al mismo tiempo, Rust se define como un lenguaje confiable, y esta confiablidad viene dada por características como las siguientes
**** Revisión de tipos esstáticos
**** Un sistema de datos seguro (si el compilador te dice que es cierto tipo, entonces lo es )
**** Tiene datos reales, nada de `any` (alo! Typescript)
**** No incluye el ["error del billon de dolares"](https://www.youtube.com/watch?v=ybrQvs4x0Ps), es decir, no existen referencias `null` ni `undefined` ni similares.
**** Tiene un compilador que de verdad entrega ayuda cuando existen errores
**** Es un lenguaje con datos inmutables por defecto, pero ofrece formas de modicar este comportamiento
**** Tiene seguros de acceso a memorio **no data races**
**** Si compila, usualmente significa que funciona
***
Rust es un lenguaje complejo, con muchos conceptos que aprende, pero tiene una comunidad bastante activa lo que ayuda mucho a la hora de aprender, actualmente podemos encontrar 6 grandes conferencias, además su desarrollo es constante contanto con varios developers full-time y una gran cantidad de colaboradores.

Un ejemplo de código en Rust, para pattern matching.
#+BEGIN_SRC rust
enum Coin {
    Penny,
    Nickel,
    Dime,
    Quarter,
}

fn value_in_cents(coin: Coin) -> u8 {
    match coin {
        Coin::Penny => 1,
        Coin::Nickel => 5,
        Coin::Dime => 10,
        Coin::Quarter => 25,
    }
}
#+END_SRC
*** [[file:20200920112829-elm.org][Elm]]
**** Un lenguaje disfrutante para crear aplicaciones web confiables
**** Puede ser considerado una alternativa a Javascript
**** Se utiliza para construir aplicaciones web
**** Disfrutable: Elm se enfoca en DX y ergonómicos: Gran compilador y mensajes de error
**** Enfocado en un compilador rápdio, friendly
**** Es pequeño y simple
**** JS interop
**** packages, editor plugin, mateiral de aprendizaje
**** Comparado con JS frameworks lo que no es correcto, Elm es un lenguaje, con los frameworks escribes JS/TS
***** Pero Elm tiene todo incluido, no se requiere un framework, Elm es el framework en si mismo.
**** Nacido el 2012 single dev. ahora tiene un Core Team y un BDFL
***** “What is Success?” youtu.be/uGlzRt-FYto (Evan Czaplinsky - creador)
***** 1 full time dev
***** small, simple, release del compilador poco
**** Elm tiene 5 conferencias. Healthy community (Menor que JS)
**** Reliable/Confiabilidad
***** Static type-checking
***** sound type system (si el compilador dice que es el tipo, entonces lo es)
****** obviamente si se usa interop con C podria no ser cierto
***** No `any` (strict mode)
***** No "billion dolar mistak" (null)
***** Helpful compilers
****** Incluye mensajes de error que incluso te dicen como reparar el error
***** If it compiles, it usually works.
***** Immutable by default: 100% immutable, pure function language
***** Elm compiled bundle size is one of the smaller
***** No runtime exceptions:
****** El compilador lo evita gracias al sistema de tipado
****** Es posible pero demasiado dificil o extraño que ocurra, a menos que exista interop con JS
*** [[file:20200920163655-elixir.org][Elixir]]
**** Nacido el 2011 por José Valim, parte del equipo Core de RoR
**** Un lenguaje dynámico y funcional para construir aplicaciones escalables yu mantenibles
**** Toma el poder de la VM Erlang conocida por ejecutar sistemas distribuidos de baja latencia
**** Se utiliza para desarrolo web, software embebido, procesamiento multimedia, ena
**** Enfocado en Escalabilidad, tolerancia a fallo y concurrencia
**** Completamente funcional
**** 100% Immutable
**** Incluye extensibilidad mendiante el uso de un DSL
**** REPL y manejador de paquetes
**** Compatible con Erlang
**** Tiene una comunidad activa y una gran conferencia llama ElixirConf en total hay 13 grandes eventos a nivel mundial.
**

*** [[file:20200922032244-clojure.org][Clojure]]
:PROPERTIES:
:ID:       8c53485f-f2f7-472a-a2bd-3b7950b47caf
:END:
**** Nacido el 2007, actualmente mantenido por Cognitect con 126 contributors formales
**** Un lenguaje robusto, practico y rápido con caracterísiticas para forma una herramienta simple, coherente y poderosa.
**** De propósito general,
**** Interoperabilidad con Java
**** Es un dialecto de Lisp y comparte la filosofía codigo-como-datos
***** Esto se conoce como homoiconocidad. El propio programa ecrito puede ser manipulado como data usando el propio lenguaje.
**** Funcional
**** Estructuras de datos inmutables
**** Polimorfismo
**** Soporta Macros
***** Provee la oporatuniad de extender el lenguaje
****** Confiable and Battle tested: Utilizado por Citibank, Simple, Amazon, Netflix, etc.
**** Se ejecuta en la JVM
**** Gran comunidad, un ejemplod ello es el project ClojureFam del que participo para aprender Clojure
**** Tiene dos conferencias anuales US para un total de entre 7 y 8 conferencias mundiales (incluyendo una remota)
**** También puede ser usado en el browser con Clojurecript, un compilador de Clojure que crea código JS


** TODO Summary
